# docker build -t maksim1990/dashboard-ui:latest -f ./docker/nuxt/Dockerfile_k8s .
# docker push maksim1990/dashboard-ui:latest
FROM alpine

# create destination directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add --update nodejs npm git

# copy the app, note .dockerignore
COPY . /usr/src/nuxt-app/
RUN cp ./deploy/.env.k8s ./.env
RUN npm install

# build necessary, even if no static files are needed,
# since it builds the server as well
RUN npm run build

# expose 5000 on container
EXPOSE 5000

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=5000

# start the app
CMD [ "npm", "start" ]
