version: '3.5'

services:
  webmastery_school_frontend:
        build:
            context: ./
            dockerfile: ./docker/nuxt/Dockerfile
        container_name: skillsmaster
        ports:
          - "3030:5000"
        networks:
          - default
          - docker-shared-services


networks:
  docker-shared-services:
    external: true
  default:
    external:
      name: nginx-proxy
